name: Notify Agent on Issue
on:
  issue_comment:
    types: [created]

jobs:
  trigger-agent:
    if: ${{ github.event.comment.body == 'implement' }}
    runs-on: ubuntu-latest
    steps:
      - name: Call Agent Repository
        uses: quochuydev/x-agent
        with:
          repository: quochuydev/x-app-1
          event-type: generate-code
          client-payload: |
            {
              "repo": "${{ github.repository }}",
              "issue_title": "${{ github.event.issue.title }}",
              "issue_body": "${{ github.event.issue.body }}",
              "issue_number": "${{ github.event.issue.number }}"
            }
